development:
  adapter: postgresql
  database: ajax_development
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  database: ajax_production
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  database: ajax_test
  pool: 5
  username:
  password:
